Repository fordes123/ITEM, pull requests merged in 2025-04, with the labels that each got.

#50 fix: 修复自动适配主题失效 问题，选择主题后自动关闭选择面板
  assets/js/script.js
  assets/js/script.min.js
Labels: fix

#52 feat(): 新增时间线分页页大小配置项
  theme/functions.php
  theme/timeline.php
Labels: feature

#54 perf(): 改进设置项
  theme/functions.php
  theme/libs/Badge.php
Labels: maintenance

#61 fix(): 修复子分类的展示方式无法正常保存
  theme/functions.php
Labels: fix

#62 perf(): 后台界面资源外部化
  src/js/backend-ui.js
  src/scss/backend-ui.scss
  src/scss/components/_nav.scss
  theme/libs/Badge.php
  webpack.config.js
Labels: maintenance

#63 ci(): 改进工作流构建流程
  .github/workflows/build.yaml
  README.md
Labels: ignore
